# Generated by Django 3.2.25 on 2024-11-04 09:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ticket_price', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('image', models.ImageField(blank=True, default='../default_post_b29qkk', upload_to='images/')),
                ('category', models.CharField(choices=[('concert', 'Concert'), ('party', 'Party'), ('festival', 'Festival'), ('exhibition', 'Exhibition'), ('workshop', 'Workshop'), ('meetup', 'Meetup'), ('conference', 'Conference'), ('networking', 'Networking'), ('seminar', 'Seminar'), ('webinar', 'Webinar'), ('charity', 'Charity'), ('sports', 'Sports'), ('food_drink', 'Food & Drink'), ('health_wellness', 'Health & Wellness')], default='meetup', max_length=30)),
                ('event_date', models.DateField(help_text='Date of the event')),
                ('start_time', models.TimeField(help_text='Start time of the event')),
                ('end_time', models.TimeField(help_text='End time of the event')),
                ('location', models.CharField(max_length=255)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
